import os
import re
import subprocess
import tempfile
from html import unescape
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import (
    NoTranscriptFound,
    TranscriptsDisabled,
    VideoUnavailable,
)


def format_timestamp(seconds: float) -> str:
    total_seconds = int(seconds)
    hours, remainder = divmod(total_seconds, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours > 0:
        return f"{hours:02d}:{minutes:02d}:{secs:02d}"
    return f"{minutes:02d}:{secs:02d}"


def parse_vtt_to_timestamped_lines(vtt_path: str) -> list[str]:
    lines = []
    current_timestamp = None
    current_text = []

    with open(vtt_path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line == "WEBVTT":
                if current_timestamp and current_text:
                    joined_text = " ".join(current_text)
                    joined_text = re.sub(r"<[^>]+>", "", joined_text)
                    joined_text = unescape(joined_text).strip()
                    if joined_text:
                        lines.append(f"[{current_timestamp}] {joined_text}")
                current_timestamp = None
                current_text = []
                continue

            if "-->" in line:
                start_time = line.split("-->")[0].strip()
                start_time = start_time.split(".")[0]
                if start_time.startswith("00:"):
                    start_time = start_time[3:]
                current_timestamp = start_time
                continue

            # Skip numeric cue IDs
            if line.isdigit():
                continue

            if current_timestamp:
                current_text.append(line)

    # Flush trailing cue if no blank line at EOF
    if current_timestamp and current_text:
        joined_text = " ".join(current_text)
        joined_text = re.sub(r"<[^>]+>", "", joined_text)
        joined_text = unescape(joined_text).strip()
        if joined_text:
            lines.append(f"[{current_timestamp}] {joined_text}")

    return lines


def fetch_with_ytdlp(video_id: str) -> list[str]:
    video_url = f"https://www.youtube.com/watch?v={video_id}"
    with tempfile.TemporaryDirectory(prefix=f"yt_subs_{video_id}_") as temp_dir:
        output_template = os.path.join(temp_dir, "%(id)s.%(ext)s")
        cmd = [
            "yt-dlp",
            "--skip-download",
            "--write-auto-subs",
            "--write-subs",
            "--sub-langs",
            "en.*",
            "--sub-format",
            "vtt",
            "-o",
            output_template,
            video_url,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "yt-dlp failed")

        candidates = [
            name for name in os.listdir(temp_dir)
            if name.startswith(video_id) and name.endswith(".vtt")
        ]
        if not candidates:
            raise RuntimeError("No VTT subtitles generated by yt-dlp")

        # Prefer manual subtitles if both manual + auto exist.
        candidates.sort(key=lambda n: ("live_chat" in n, ".en." not in n, ".en-orig." not in n, n))
        vtt_path = os.path.join(temp_dir, candidates[0])
        parsed = parse_vtt_to_timestamped_lines(vtt_path)
        if not parsed:
            raise RuntimeError("Generated VTT was empty after parsing")
        return parsed


def run_task():
    video_ids = [
        "Iz6nlTnZfJE", "CM_HDRF4y0s", "zknO3GkSFAg", "ZS0DqHRVb3U",
        "0UxQbhaoMlQ", "L7a694gzKG4", "o6ArIMHasXE", "_3r3QksqaiA",
        "OFL0eI4JRJk", "xeUhKuJbeWQ"
    ]
    
    output_folder = './research/youtube-transcripts/'
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    print(f"Starting transcript fetch for {len(video_ids)} videos...\n")

    api = YouTubeTranscriptApi()

    for v_id in video_ids:
        file_path = os.path.join(output_folder, f"{v_id}.md")
        try:
            print(f"Fetching ID: {v_id}...")

            data = api.fetch(v_id, languages=["en"])
            transcript_lines = []
            for entry in data:
                text = entry.text if hasattr(entry, "text") else entry["text"]
                start = entry.start if hasattr(entry, "start") else entry.get("start", 0)
                transcript_lines.append(f"[{format_timestamp(start)}] {text}")
            source = "youtube-transcript-api"

        except (NoTranscriptFound, TranscriptsDisabled, VideoUnavailable, Exception) as e:
            print(f"INFO: API fetch failed for {v_id} ({e})")
            try:
                transcript_lines = fetch_with_ytdlp(v_id)
                source = "yt-dlp subtitles fallback"
                print("OK: fallback fetched")
            except Exception as fallback_error:
                print(f"ERROR: {v_id}: fallback failed: {fallback_error}")
                continue

        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(f"# {v_id}\n\n")
                f.write(f"Source: {source}\n\n")
                f.write("\n".join(transcript_lines))
            print("OK: saved")
        except Exception as e:
            print(f"ERROR: {v_id}: write failed: {e}")

    print("\nDone.")

if __name__ == "__main__":
    run_task()